name: Lint GitHub Actions Workflows

on:
  push:
    # paths: [".github/workflows/*.yml", ".github/workflows/*.yaml"]

defaults: # デフォルトシェル 
  run:
    shell: bash

concurrency: # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run actionlint
        run: |
            docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest

  log:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo '::debug:: Linting completed successfully.'